from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
first=['inventory-supabase-schema.sql','orders.sql','orders_nexus_tax.sql','orders_admin_rls.sql','discount_codes.sql','patch-orders-columns.sql','patch-manual-orders.sql','patch-walk-in-orders.sql','patch-orders-payment-flow.sql','patch-orders-fulfillment-lifecycle.sql','patch-orders-quoted-shipping.sql','patch-orders-checkout-quote-columns.sql','patch-orders-admin-fulfillment-workflow.sql','patch-orders-shippo-schema-complete.sql','patch-orders-shippo-sync.sql','patch-order-shippo-labels.sql','patch-incoming-inventory-batches.sql','patch-incoming-batch-status-on-hold.sql','patch-incoming-batch-receive-rpc.sql']
last=['patch-walk-in-order-complete.sql','patch-checkout-payment-idempotency.sql','patch-online-payment-inventory-atomic.sql','patch-shipping-phase6-hardening.sql','patch-online-automatic-label-lifecycle.sql','patch-admin-staff-authorization.sql']
exclude={'hotfix-retire-hardin-discount-campaign-2026-08-21.sql','sandbox-bootstrap.generated.sql'}
others=sorted(p.name for p in (root/'sql').glob('*.sql') if p.name not in set(first+last)|exclude)
files=first+others+last
files.remove('patch-orders-external-docs-multiline-paths.sql')
files.insert(files.index('patch-orders-manual-external-fulfillment.sql')+1,'patch-orders-external-docs-multiline-paths.sql')
sql="""-- SANDBOX ONLY: swincstzhatcrsbobngx. Never run on the production project.
-- Generated from repository SQL; no customer/order data is copied.
begin;
do $$ begin
 if to_regclass('public.orders') is not null or to_regclass('public.products') is not null then
   raise exception 'Sandbox initializer requires an empty store schema';
 end if;
end $$;
"""
for name in files:
 s=(root/'sql'/name).read_text()
 if name=='orders.sql':
  s=s.replace('id uuid primary key default gen_random_uuid(),','id bigint generated by default as identity primary key,',1)
 sql+='\n-- SOURCE: '+name+'\n'+s+'\n'
quote=lambda s:"'"+s.replace("'","''")+"'"
data=json.loads((root/'data/store.json').read_text())
for p in data['products']:
 sql+=f"insert into public.products (slug,name) values ({quote(p['slug'])},{quote(p['name'])});\n"
 for size in p['supportedSizes']:
  sql+=f"insert into public.product_variants (product_id,size_label,boxes_per_case,gloves_per_box) select id,{quote(size)},10,100 from public.products where slug={quote(p['slug'])};\n"
sql+="""
-- Disposable stock only: two cartons and five loose boxes per supported size.
insert into public.inventory_levels (variant_id,cases_on_hand,boxes_loose_on_hand,cases_baseline,boxes_baseline)
select id,2,5,2,5 from public.product_variants;
-- Explicit sandbox marker for subsequent configuration checks.
insert into public.admin_runtime_settings (setting_key,setting_value)
values ('sandbox_identity','{"projectRef":"swincstzhatcrsbobngx","purpose":"disposable checkout validation"}'::jsonb);
commit;
select 'sandbox_initialized' as result,
 (select count(*) from public.products) as products,
 (select count(*) from public.product_variants) as variants,
 (select count(*) from public.orders) as orders;
"""
(root/'sql/sandbox-bootstrap.generated.sql').write_text(sql)
print(f'Generated {len(files)} schema scripts plus disposable inventory; {len(sql)} characters.')
