-- Phase 6 shipping hardening: cross-instance label purchase claim + health telemetry.
-- Idempotent. Run in the Supabase SQL Editor before enabling production label purchases.

alter table public.orders
  add column if not exists shippo_label_purchase_claim_id text,
  add column if not exists shippo_label_purchase_claimed_at timestamptz,
  add column if not exists shippo_label_purchase_last_error text;

comment on column public.orders.shippo_label_purchase_claim_id is
  'Opaque claim token preventing concurrent Shippo label purchases across server instances.';
comment on column public.orders.shippo_label_purchase_claimed_at is
  'Time the current Shippo label purchase claim was acquired; stale claims may be reclaimed.';
comment on column public.orders.shippo_label_purchase_last_error is
  'Allowlisted outcome code from the most recent label purchase attempt; never raw provider data.';

create index if not exists orders_shippo_label_purchase_claim_idx
  on public.orders (shippo_label_purchase_claimed_at)
  where shippo_label_purchase_claimed_at is not null;

create table if not exists public.shipping_health_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('checkout_rate', 'admin_rate', 'label_purchase')),
  outcome text not null check (outcome in ('success', 'no_rates', 'fallback', 'partial', 'failed', 'locked')),
  provider text not null default 'shippo',
  order_id bigint references public.orders (id) on delete set null,
  error_code text,
  parcel_count integer,
  rate_count integer,
  duration_ms integer,
  created_at timestamptz not null default now()
);

create index if not exists shipping_health_events_created_idx
  on public.shipping_health_events (created_at desc);
create index if not exists shipping_health_events_outcome_idx
  on public.shipping_health_events (outcome, created_at desc);

comment on table public.shipping_health_events is
  'Sanitized operational shipping outcomes. Never stores addresses, tokens, payloads, or customer data.';

alter table public.shipping_health_events enable row level security;

drop policy if exists "Staff can read shipping_health_events" on public.shipping_health_events;
create policy "Staff can read shipping_health_events"
  on public.shipping_health_events
  for select
  to authenticated
  using (true);

notify pgrst, 'reload schema';
