-- v2.5 online checkout: signed quote snapshots and durable per-package label recovery.
-- Idempotent. Review and apply in Supabase before enabling automatic label purchasing.
-- Do not apply this file to production as part of a code deploy without a separate DB change review.

alter table public.orders
  add column if not exists checkout_quote_correlation_id text,
  add column if not exists checkout_quote_expires_at timestamptz,
  add column if not exists checkout_quote_fingerprint text,
  add column if not exists checkout_quote_snapshot_json jsonb,
  add column if not exists selected_shipping_rate_snapshot_json jsonb,
  add column if not exists label_workflow_updated_at timestamptz,
  add column if not exists label_workflow_error_code text;

alter table public.order_shippo_labels
  add column if not exists purchase_attempt_id uuid,
  add column if not exists claim_id uuid,
  add column if not exists claimed_at timestamptz,
  add column if not exists claim_expires_at timestamptz,
  add column if not exists attempt_count integer not null default 0,
  add column if not exists next_retry_at timestamptz,
  add column if not exists purchase_started_at timestamptz,
  add column if not exists purchased_at timestamptz,
  add column if not exists last_transition_at timestamptz,
  add column if not exists last_error_code text;

alter table public.order_shippo_labels drop constraint if exists order_shippo_labels_status_check;
alter table public.order_shippo_labels add constraint order_shippo_labels_status_check
  check (status in (
    'pending', 'processing', 'purchased', 'failed', 'skipped',
    'retry', 'unknown', 'admin_review_required'
  ));

create unique index if not exists order_shippo_labels_order_parcel_uidx
  on public.order_shippo_labels (order_id, parcel_index);
create unique index if not exists order_shippo_labels_attempt_uidx
  on public.order_shippo_labels (purchase_attempt_id)
  where purchase_attempt_id is not null;
create index if not exists order_shippo_labels_recovery_idx
  on public.order_shippo_labels (status, next_retry_at, claim_expires_at);

create or replace function public.claim_order_shippo_label_package(
  p_order_id bigint,
  p_parcel_index integer,
  p_parcel_count integer,
  p_attempt_id uuid,
  p_claim_id uuid,
  p_claim_expires_at timestamptz,
  p_rate_object_id text,
  p_shipment_object_id text,
  p_parcel_metadata jsonb
)
returns setof public.order_shippo_labels
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.order_shippo_labels (
    order_id, parcel_index, parcel_count, purchase_attempt_id,
    selected_rate_object_id, shipment_object_id, parcel_metadata,
    status, created_at, updated_at, last_transition_at
  ) values (
    p_order_id, p_parcel_index, p_parcel_count, p_attempt_id,
    nullif(trim(p_rate_object_id), ''), nullif(trim(p_shipment_object_id), ''), p_parcel_metadata,
    'pending', now(), now(), now()
  ) on conflict (order_id, parcel_index) do nothing;

  return query
  update public.order_shippo_labels l
  set claim_id = p_claim_id,
      claimed_at = now(),
      claim_expires_at = p_claim_expires_at,
      purchase_attempt_id = coalesce(l.purchase_attempt_id, p_attempt_id),
      selected_rate_object_id = coalesce(l.selected_rate_object_id, nullif(trim(p_rate_object_id), '')),
      shipment_object_id = coalesce(l.shipment_object_id, nullif(trim(p_shipment_object_id), '')),
      parcel_metadata = coalesce(l.parcel_metadata, p_parcel_metadata),
      status = 'processing',
      attempt_count = l.attempt_count + 1,
      purchase_started_at = now(),
      last_transition_at = now(),
      updated_at = now(),
      error_message = null,
      last_error_code = null
  where l.order_id = p_order_id
    and l.parcel_index = p_parcel_index
    and l.status in ('pending', 'retry', 'processing')
    and (l.claim_expires_at is null or l.claim_expires_at < now())
  returning l.*;
end;
$$;

revoke all on function public.claim_order_shippo_label_package(bigint,integer,integer,uuid,uuid,timestamptz,text,text,jsonb) from public;
grant execute on function public.claim_order_shippo_label_package(bigint,integer,integer,uuid,uuid,timestamptz,text,text,jsonb) to service_role;

create table if not exists public.shipping_state_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  parcel_index integer,
  correlation_id text,
  from_status text,
  to_status text not null,
  reason_code text,
  created_at timestamptz not null default now()
);
create index if not exists shipping_state_events_order_idx
  on public.shipping_state_events (order_id, created_at desc);

create table if not exists public.square_webhook_events (
  event_id text primary key,
  payment_id text,
  order_id bigint references public.orders(id) on delete set null,
  processed_at timestamptz not null default now()
);
create unique index if not exists square_webhook_events_payment_order_uidx
  on public.square_webhook_events (payment_id, order_id)
  where payment_id is not null and order_id is not null;

alter table public.orders drop constraint if exists orders_order_status_check;
alter table public.orders add constraint orders_order_status_check check (order_status in (
  'draft', 'payment_link_sent', 'awaiting_payment', 'payment_processing', 'paid',
  'paid_label_pending', 'label_processing', 'labels_purchased', 'ready_to_fulfill',
  'paid_label_retry', 'label_purchase_unknown', 'partial_label_failure',
  'admin_review_required', 'ready_to_ship', 'partial_label_purchase',
  'label_purchased', 'ready_for_pickup', 'ready_for_local_delivery',
  'shipped', 'cancelled'
));

create or replace function public.online_order_payment_complete(
  p_order_id text,
  p_payment_id text,
  p_paid_total_cents integer,
  p_inventory_ops jsonb,
  p_customer_address text default null,
  p_buyer_email text default null,
  p_buyer_phone text default null,
  p_buyer_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.orders%rowtype;
  v_subtotal integer;
  v_tax integer;
  v_shipping integer;
  v_now timestamptz := now();
begin
  if nullif(trim(coalesce(p_order_id, '')), '') is null
     or nullif(trim(coalesce(p_payment_id, '')), '') is null then
    raise exception 'Order and payment are required.' using errcode = 'P0001';
  end if;
  if p_paid_total_cents is null or p_paid_total_cents < 1 then
    raise exception 'Paid total is invalid.' using errcode = 'P0001';
  end if;
  if jsonb_typeof(coalesce(p_inventory_ops, '[]'::jsonb)) is distinct from 'array' then
    raise exception 'Inventory operations are invalid.' using errcode = 'P0001';
  end if;

  select * into o from public.orders where id::text = p_order_id for update;
  if not found then
    raise exception 'Order not found.' using errcode = 'P0001';
  end if;
  if trim(coalesce(o.order_source, '')) is distinct from 'web' then
    raise exception 'Only online orders can be finalized here.' using errcode = 'P0001';
  end if;
  if lower(coalesce(o.status, '')) = 'paid' and o.inventory_committed_at is not null then
    if trim(coalesce(o.payment_id, '')) is distinct from trim(p_payment_id) then
      raise exception 'Order payment does not match.' using errcode = 'P0001';
    end if;
    return jsonb_build_object('ok', true, 'idempotent', true, 'order', to_jsonb(o));
  end if;
  if trim(coalesce(o.order_status, '')) = 'cancelled' then
    raise exception 'Cancelled order cannot be finalized.' using errcode = 'P0001';
  end if;
  if jsonb_array_length(coalesce(p_inventory_ops, '[]'::jsonb)) > 0 then
    perform public.inventory_apply_ops(p_inventory_ops);
  end if;

  v_subtotal := greatest(0, coalesce(o.subtotal_cents, 0));
  v_tax := greatest(0, coalesce(o.tax_cents, 0));
  v_shipping := greatest(0, p_paid_total_cents - v_subtotal - v_tax);

  update public.orders
  set status = 'paid',
      order_status = 'paid_label_pending',
      payment_id = trim(p_payment_id),
      total_cents = p_paid_total_cents,
      shipping_cents = v_shipping,
      paid_shipping_amount_cents = v_shipping,
      customer_address = coalesce(nullif(trim(p_customer_address), ''), customer_address),
      customer_email = coalesce(nullif(trim(p_buyer_email), ''), customer_email),
      customer_phone = coalesce(nullif(trim(p_buyer_phone), ''), customer_phone),
      customer_name = coalesce(nullif(trim(p_buyer_name), ''), customer_name),
      inventory_committed_at = v_now,
      payment_reconciliation_required = false,
      payment_reconciliation_error = null,
      updated_at = v_now
  where id::text = p_order_id
  returning * into o;

  return jsonb_build_object('ok', true, 'idempotent', false, 'order', to_jsonb(o));
end;
$$;

revoke all on function public.online_order_payment_complete(text,text,integer,jsonb,text,text,text,text) from public;
grant execute on function public.online_order_payment_complete(text,text,integer,jsonb,text,text,text,text) to service_role;

notify pgrst, 'reload schema';
